### ISSUE TITLE
Editing people and companies

### ISSUE THREAD

**Issue by ari** [ishgroup/lightbook#10]
Once everything else is working, we can allow for editing records. I'd like this to be a separate "edit mode" since the system is 1% editing to 99% viewing.

**Comment by ari** [comment]
Chintan, I think the next priority here is to display the company and person details in a non-edit view, without lightbox. Can we display all the fields from json without enumerating what they are? That is, just displaying whatever data we get? Then we can add more fields to LDAP without changing React.

**Comment by chintankotadia** [comment]
@ari : Lightbox has been removed and all the details are shown in expand and collapse mode. Can you please provide me list of all the fields which you would like to have so that I can configure it in reactjs?

At the moment, add and update functionality is ready in reactjs. @k41n just need to implement that one in python. Sample data is present in development.py for reference.

**Comment by ari** [comment]
@chintankotadia Looking good. Can I suggest some cosmetic improvements.

1. Make the labels look more like labels (smaller, grey)
2. Remove items with no data
3. Slide the view when clicking on a name to give better visual clue as to what happened
4. Make the name you are expanding visually part of the block (for example, by giving it a white background)
5. Tighten the line spacing
6. Remove the delete icon from the list view and put it only on the edit view (after you press the edit button)
7. Put the dragonfly button onto the detail view (not the list view)
5.

**Comment by chintankotadia** [comment]
@ari : I am done with all the points except point no. 6. I am working on it.
