### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ari** [ishgroup/lightbook#11]
As part of being able to edit/add records, we'll need to wrap authentication around the whole app. This will be against records in ou=Employees,ou=People,dc=ish,dc=com,dc=au

Then we can bind to LDAP with that user in order to make modifications.

**Comment by k41n** [comment]
@ari, I implemented basic authentication, but now it is working slowly because we need to use dn and password for authentication in ldap . Now dn for employees looks like: "uidNumber=9999,ou=Customers,ou=People,dc=ish,dc=com,dc=au". Therefore script finds a user with a specified username(uid), and after that authenticates him.
So we have 1 extra connection and 1 extra request to ldap. We can improve it if dn for employees will be changed to correct attrubute(uid,email or something else).

**Comment by ari** [comment]
Changing the dn right now would involve changing too many other things. Performance is OK and if we really have to, we could cache the dn in a cookie. But I don't see a problem at the moment.
